<a href="https://colab.research.google.com/github/aritraM23/TFlow/blob/main/learningTF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#a tensor is an n-dim array of data
# 1d : vector
# 2d : matrix
# etc.

#initialisation of tensors
x = tf.constant(4)
# print(x) => tf.Tensor(4, shape=(), dtype=int32)...this has no shape
#we can also specify the shape

y = tf.constant(4, shape = (1,1))
#print(y) => tf.Tensor([[4]], shape=(1, 1), dtype=int32)

x = tf.ones((3,3))
# print(x)

# tf.Tensor(
# [[1. 1. 1.]
#  [1. 1. 1.]
#  [1. 1. 1.]], shape=(3, 3), dtype=float32)..same will be case for tf.zeros

# tf.eye(n) makes an identity matrix of dimension 1

x = tf.random.normal((3,3), mean  = 0, stddev= 1)
#above is for normal dist of values across tensors

x = tf.random.uniform((1,3),minval = 0, maxval = 1)
#gives tensor with random values from 0 to 1 

x = tf.range(9) # => tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)

x = tf.range(start= 1, limit = 10,delta = 2) 
#print(x) => #tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)

#although type can be specified while initialisation, it can be casted too
x = tf.cast(x, dtype = tf.float64)
#print(x) -> tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)
#tf.float(16,32,64), tf.int(8,16,32,64), tf.bool

#mathematical operations
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

z = tf.add(x,y) #-> tf.Tensor([10 10 10], shape=(3,), dtype=int32)
#z = x+y also works
#for subtraction, z = x-y or tf.subtract(x,y)

#for division, elementwise division : tf.divide(x,y)
#or z = x/y

#for multiplication, z = tf.multiply(x,y)
#or z = x*y

z = tf.tensordot(x, y, axes = 1) #->tf.Tensor(46, shape=(), dtype=int32)
#print(z)#this will do element wise multiplication and them add them
#other way of achieving the same is:
# z = tf.reduce_sum(x*y, axis = 0)
# print(z) -> tf.Tensor(46, shape=(), dtype=int32)

z = x ** 5 #element wise exponantiation
#print(z) -> tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
 
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y) #matrix multiplication, it can also be done by using  z = x@y

#indexing
x = tf.constant([0,1,2,3,4,5])
# print(x[:]) #this will print all the elements
# print(x[1:]) #normal slicing rules, everything except first element
# print(x[1:3])#prints from 1 to 3
# #suppose we wanna skip one element alternatively
# print(x[::2])
print(x[::-1]) #reverse order

#how to print a sub set of the array with desrired values
indices = tf.constant([0,2])
x_ind = tf.gather(x, indices)
print(x_ind)

x = tf.constant([[1,2],
                [3,4]])

print(x[0,1:]) #0th row and all columns except first

#reshaping
x = tf.range(9)

x = tf.reshape(x , (3,3)) #reshaping
print(x)

x = tf.transpose(x, perm=[1,0])
print(x)


tf.Tensor([5 4 3 2 1 0], shape=(6,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [ ]:
#building basic neural nets

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#print(x_train.shape)
#now we'd need to flatten them to have only one long column for those feature values
#so we reshape it to same num of rows and change it to

x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

#Sequential API of keras(very convenient but not very flexible)
model = keras.Sequential(
    [
      #keras.Input(shape = (28*28)), #this sends a demo input to be able to let model print its summary
     layers.Dense(512, activation = 'relu'),
     layers.Dense(256, activation = 'relu'),
     layers.Dense(10),
    ]
)

# print(model.summary()) #model.summary is a common debugging tool
# import sys
# sys.exit()

# another way of adding layers is :
model = keras.Sequential()
model.add(keras.Input(shape=(784)))
model.add(layers.Dense(512, activation = 'relu'))
model.add(layers.Dense(256, activation = 'relu'))
model.add(layers.Dense(10))

#extracting specific layer outputs:
# model = keras.Model(inputs = model.inputs,
#                     outputs = [model.layers[-1].output]) #index value decides which layer to take, -1 means last, -2 means second last and henceforth
#if there are names of the layers by name argument, then they can be accessed in te=he following way:
#[model.get_layer('name of the layer').output]

#for all layers, outputs = [layer.output for layer in model.layers]
#features = model.predict(x_train)
#for feature in features:
#   print(feature.shape)


# feature = model.predict(x_train)
# print(feature.shape)
# import sys
# sys.exit()

#Functional API (A bit more flexible)
inputs = keras.Input(shape = (784))
x = layers.Dense(512, activation = 'relu')(inputs)
x = layers.Dense(256, activation = 'relu')(x)
outputs = layers.Dense(10, activation = 'softmax')(x)
model = keras.Model(inputs = inputs, outputs = outputs)

#compile is about the specifications of the model
model.compile(
    #Use this crossentropy loss function when there are two or more label classes. 
    #We expect labels to be provided as integers.
    #from_logits is true to send the last layer through a softmax activation first
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits= False), 
    optimizer = keras.optimizers.Adam(lr = 0.001),
    metrics = ["accuracy"],
)

#fit is more about training and preparing it
model.fit(x_train, y_train, batch_size = 32, epochs = 5, verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)



11501568/11490434 [==============================] - 0s 0us/step


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/5
1875/1875 - 10s - loss: 0.1869 - accuracy: 0.9444
Epoch 2/5
1875/1875 - 9s - loss: 0.0811 - accuracy: 0.9750
Epoch 3/5
1875/1875 - 9s - loss: 0.0549 - accuracy: 0.9819
Epoch 4/5
1875/1875 - 9s - loss: 0.0407 - accuracy: 0.9868
Epoch 5/5
1875/1875 - 9s - loss: 0.0326 - accuracy: 0.9895
313/313 - 1s - loss: 0.0762 - accuracy: 0.9795


[0.07616499066352844, 0.9794999957084656]

In [ ]:
#Convolutional Networks

import tensorflow as tf
import math
from tensorflow import keras
from tensorflow.keras import layers, regularizers
from tensorflow.keras.datasets import cifar10
#cifar10 is a dataset consisting of 10 classes of objects with 50k training images & 10k test images with 32*32 RGB
e = math.e

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0 
#this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.astype("float32") / 255.0

#since it is convolutional so we're not going to flatten it
#sequential api approach
# model = keras.Sequential(
#     [
#       keras.Input(shape=(32,32,3)),
#       layers.Conv2D(32,3, padding = 'valid', activation = 'relu'),
#       layers.MaxPooling2D(pool_size = (2,2)),
#       layers.Conv2D(64,3,activation = 'relu'),
#       layers.MaxPooling2D(),
#       layers.Conv2D(128, 3, activation = 'relu'),
#       layers.Flatten(),
#       layers.Dense(64,activation = 'relu'),
#       layers.Dense(10),
#     ]
# )

#functional api, with batch normalisation
def my_model():
  #l2 is a batch normalisation method as well
  inputs = keras.Input(shape=(32,32,3))
  x = layers.Conv2D(
      32,3, padding = 'same', kernel_regularizer = regularizers.l2(0.01),            
                    )(inputs)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.MaxPooling2D()(x)
  x = layers.Conv2D(
      64, 3,padding = 'same', kernel_regularizer = regularizers.l2(0.01),
      )(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Conv2D(
      128,3,padding = 'same', kernel_regularizer = regularizers.l2(0.01),
      )(x)
  x = layers.BatchNormalization()(x)
  x = keras.activations.relu(x)
  x = layers.Flatten()(x)
  x = layers.Dense(
      64 , activation='relu', kernel_regularizer = regularizers.l2(0.01),
      )(x)
  x = layers.Dropout(0.5)(x) #drops .5 part of the connections in b/w those layers
  outputs = layers.Dense(10)(x)
  model = keras.Model(inputs = inputs , outputs = outputs)
  return model

model = my_model()
#print(model.summary())
#when overfitting, we regularise the model by using dropout, early stoppage etc
# for that we import regularizers from keras
model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits= True),
    optimizer = keras.optimizers.Adam(lr = 3*e - 4),
    metrics = ["accuracy"],
)

model.fit(x_train, y_train,batch_size=64,epochs = 10, verbose = 2)
model.evaluate(x_test, y_test, batch_size= 64, verbose = 2)


In [ ]:
#Recurring Neural Networks

import tensorflow as tf
from tensorflow import keras
import math
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

e = math.e
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.astype("float32") / 255.0

#in the first timestamp it'll send the first row and in 2nd, second row shall be sent etc.
model = keras.Sequential()
model.add(keras.Input(shape = (None, 28))) #28 timestamps, none is here because we don't need a specific timestamp...28 pixels for each timestamp
model.add(
    layers.SimpleRNN(256, return_sequences = True, activation = 'tanh') #multiple RNN layers on top of each other shall be stacked 
) #default activation is tanh
model.add(layers.SimpleRNN(256, activation = 'tanh'))
model.add(layers.Dense(10))

model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits= True),
    optimizer = keras.optimizers.Adam(lr = 0.001),
    metrics = ["accuracy"],
)

model.fit(x_train, y_train,batch_size=64,epochs = 10, verbose = 2)
model.evaluate(x_test, y_test, batch_size= 64, verbose = 2)

#to build a GRU or LSTM, we just have to change SimpleRNN to GRU or LSTM and it will all be the same

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Epoch 1/10
938/938 - 91s - loss: 0.2962 - accuracy: 0.9109
Epoch 2/10
938/938 - 89s - loss: 0.1875 - accuracy: 0.9449
Epoch 3/10
938/938 - 89s - loss: 0.1682 - accuracy: 0.9516
Epoch 4/10
938/938 - 89s - loss: 0.1388 - accuracy: 0.9596
Epoch 5/10
938/938 - 90s - loss: 0.1401 - accuracy: 0.9600
Epoch 6/10
938/938 - 90s - loss: 0.1416 - accuracy: 0.9594
Epoch 7/10
938/938 - 90s - loss: 0.1279 - accuracy: 0.9644
Epoch 8/10
938/938 - 90s - loss: 0.1422 - accuracy: 0.9603
Epoch 9/10
938/938 - 90s - loss: 0.1200 - accuracy: 0.9654
Epoch 10/10
938/938 - 92s - loss: 0.1281 - accuracy: 0.9636
157/157 - 5s - loss: 0.1111 - accuracy: 0.9679


[0.11112425476312637, 0.9678999781608582]

In [ ]:
#Bidirectional LSTM

import tensorflow as tf
from tensorflow import keras
import math
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

e = math.e
(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = x_train.astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.astype("float32") / 255.0

#in the first timestamp it'll send the first row and in 2nd, second row shall be sent etc.
model = keras.Sequential()
model.add(keras.Input(shape = (None, 28))) #28 timestamps, none is here because we don't need a specific timestamp...28 pixels for each timestamp
model.add(
    layers.Bidirectional(
      layers.LSTM(256, return_sequences = True, activation = 'tanh') #multiple RNN layers on top of each other shall be stacked 
    )     #since, it is bidriectional, we'll get 512 nodes instead of 256,
    #one time it will be forward, other time it will be backwards hence doubled
 ) #default activation is tanh
model.add(
    layers.Bidirectional(
      layers.LSTM(256, activation = 'tanh')
    )
)
model.add(layers.Dense(10))

print(model.summary())

model.compile(
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits= True),
    optimizer = keras.optimizers.Adam(lr = 0.001),
    metrics = ["accuracy"],
)

model.fit(x_train, y_train,batch_size=64,epochs = 10, verbose = 2)
model.evaluate(x_test, y_test, batch_size= 64, verbose = 2)


KeyboardInterrupt: ignored

In [ ]:
#depth of Functional API
import os
import tensorflow as tf
from tensorflow import keras
import math
from tensorflow.keras import layers,regularizers
from tensorflow.keras.datasets import mnist
import pandas as pd

# HYPERPARAMETERS
BATCH_SIZE = 64
WEIGHT_DECAY = 0.001
LEARNING_RATE = 0.001

# Make sure we don't get any GPU errors
# physical_devices = tf.config.list_physical_devices("GPU")
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_images = os.getcwd() + "/train_images/" + train_df.iloc[:, 0].values
test_images = os.getcwd() + "/test_images/" + test_df.iloc[:, 0].values

train_labels = train_df.iloc[:, 1:].values
test_labels = test_df.iloc[:, 1:].values


def read_image(image_path, label):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_image(image, channels=1, dtype=tf.float32)

    # In older versions you need to set shape in order to avoid error
    # on newer (2.3.0+) the following 3 lines can safely be removed
    image.set_shape((64, 64, 1))
    label[0].set_shape([])
    label[1].set_shape([])

    labels = {"first_num": label[0], "second_num": label[1]}
    return image, labels


AUTOTUNE = tf.data.experimental.AUTOTUNE
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = (
    train_dataset.shuffle(buffer_size=len(train_labels))
    .map(read_image)
    .batch(batch_size=BATCH_SIZE)
    .prefetch(buffer_size=AUTOTUNE)
)

test_dataset = tf.data.Dataset.from_tensor_slices((test_images, test_labels))
test_dataset = (
    test_dataset.map(read_image)
    .batch(batch_size=BATCH_SIZE)
    .prefetch(buffer_size=AUTOTUNE)
)

inputs = keras.Input(shape=(64, 64, 1)) #64 by 64 pixels and 1 channl cause greyscale

x = layers.Conv2D(
    filters=32,
    kernel_size=3,
    padding="same",
    kernel_regularizer=regularizers.l2(WEIGHT_DECAY),
)(inputs)
x = layers.BatchNormalization()(x)
x = keras.activations.relu(x)
x = layers.Conv2D(64, 3, kernel_regularizer=regularizers.l2(WEIGHT_DECAY),)(x)
x = layers.BatchNormalization()(x)
x = keras.activations.relu(x)
x = layers.MaxPooling2D()(x)
x = layers.Conv2D(
    64, 3, activation="relu", kernel_regularizer=regularizers.l2(WEIGHT_DECAY),
)(x)
x = layers.Conv2D(128, 3, activation="relu")(x)
x = layers.MaxPooling2D()(x)
x = layers.Flatten()(x)
x = layers.Dense(128, activation="relu")(x)
x = layers.Dropout(0.5)(x)
x = layers.Dense(64, activation="relu")(x)

#here we have the outputs for 2 diff numbers in the image which isn't possible in Sequential
output1 = layers.Dense(10, activation="softmax", name="first_num")(x)
output2 = layers.Dense(10, activation="softmax", name="second_num")(x)
model = keras.Model(inputs=inputs, outputs=[output1, output2])

model.compile(
    optimizer=keras.optimizers.Adam(LEARNING_RATE),
    loss=[
      keras.losses.SparseCategoricalCrossentropy(),
      keras.losses.SparseCategoricalCrossentropy(),
    ],
    metrics=["accuracy"],
)

model.fit(train_dataset, epochs=5, verbose=2)
model.evaluate(test_dataset, verbose=2)

Epoch 1/5


NotFoundError: ignored

In [ ]:
#Model Subclassing

#increases flexibility

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#print(x_train.shape)
#now we'd need to flatten them to have only one long column for those feature values
#so we reshape it to same num of rows and change it to

x_train = x_train.reshape(-1, 28,28,1).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28,28,1).astype("float32") / 255.0

# CNN-> BatchNornm -> ReLU (common structure)
# what if we write the structure in class because running timestamp wise would take high computational power

#subclasing is the same way of using pytorch

class CNNBlock(layers.Layer):
  def __init__(self, out_channels, kernel_size = 3):
    super(CNNBlock, self).__init__() #runs parent class layer by layer
    self.conv = layers.Conv2D(out_channels, kernel_size, padding = 'same') #Conv layer
    self.bn = layers.BatchNormalization() #BatchNorm layer

  def call(self, input_tensor, training = False):
    #call method is the forward method, which takes the input tensor and runs the layers
    x = self.conv(input_tensor)
    x = self.bn(x, training = training)
    x = tf.nn.relu(x)
    return x


model = keras.Sequential(
    [
      CNNBlock(32),
      CNNBlock(64),
      CNNBlock(128),
      layers.Flatten(),
      layers.Dense(10),
    ]
)

model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

model.fit(x_train, y_train, batch_size = 64, epochs = 3, verbose = 2)
model.evaluate(x_test, y_test, batch_size = 64, verbose = 2)

Epoch 1/3
938/938 - 738s - loss: 0.5051 - accuracy: 0.9501
Epoch 2/3
938/938 - 723s - loss: 0.0672 - accuracy: 0.9844
Epoch 3/3
938/938 - 728s - loss: 0.0318 - accuracy: 0.9902
157/157 - 29s - loss: 0.0614 - accuracy: 0.9841


[0.061383698135614395, 0.9840999841690063]

In [ ]:
#Resnet

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
#print(x_train.shape)
#now we'd need to flatten them to have only one long column for those feature values
#so we reshape it to same num of rows and change it to

x_train = x_train.reshape(-1, 28,28,1).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28,28,1).astype("float32") / 255.0

# CNN-> BatchNornm -> ReLU (common structure)
# what if we write the structure in class because running timestamp wise would take high computational power

#subclasing is the same way of using pytorch

class CNNBlock(layers.Layer):
  def __init__(self, out_channels, kernel_size = 3):
    super(CNNBlock, self).__init__() #runs parent class layer by layer
    self.conv = layers.Conv2D(out_channels, kernel_size, padding = 'same') #Conv layer
    self.bn = layers.BatchNormalization() #BatchNorm layer

  def call(self, input_tensor, training = False):
    #call method is the forward method, which takes the input tensor and runs the layers
    x = self.conv(input_tensor)
    x = self.bn(x, training = training)
    x = tf.nn.relu(x)
    return x


#creating a residula network with 3 CNN blocks
class ResBlock(layers.Layer):
  def __init__(self, channels):
    super(ResBlock, self).__init__()
    self.cnn1 = CNNBlock(channels[0])
    self.cnn2 = CNNBlock(channels[1])
    self.cnn3 = CNNBlock(channels[2])
    self.pooling = layers.MaxPooling2D()
    self.identity_mapping = layers.Conv2D(channels[1], 1, padding = 'same')

  def call(self, input_tensor, training = False):
    x = self.cnn1(input_tensor, training = training)
    x = self.cnn2(x, training = training)
    x = self.cnn3(
        x + self.identity_mapping(input_tensor), training = training,
    )
    return self.pooling(x)

class Resnet_Like(keras.Model):
  #keras.Model has added functionalities like built in training, evaluation added to the func.s of layers.Layer
  #in the final model, keras.Model is to be used
  def __init__(self, num_classes = 10):
    super(Resnet_Like, self).__init__()
    #specifying the channels for each of the CNN blocks
    self.block1 = ResBlock([32,32,64])
    self.block2 = ResBlock([128,128,256])
    self.block3 = ResBlock([128,256,512])
    self.pool = layers.GlobalAveragePooling2D()
    self.classifier = layers.Dense(num_classes)

  def call(self, input_tensor, training = False):
    x = self.block1(input_tensor, training = training)
    x = self.block2(x, training = training)
    x = self.block3(x, training = training)
    x = self.pool(x)
    return self.classifier(x)
  #function is to provide shape to the outputs in the model summary
  def model(self):
    x = keras.Input(shape = (28,28,1))
    return keras.Model(inputs = [x], outputs = self.call(x))


model = Resnet_Like(num_classes = 10)
model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

print(model.model().summary())

model.fit(x_train, y_train, batch_size = 64, epochs = 1, verbose = 2)

model.evaluate(x_test, y_test, batch_size = 64, verbose = 2)

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 28, 28, 1)]       0         
_________________________________________________________________
res_block_3 (ResBlock)       (None, 14, 14, 64)        28640     
_________________________________________________________________
res_block_4 (ResBlock)       (None, 7, 7, 256)         526976    
_________________________________________________________________
res_block_5 (ResBlock)       (None, 3, 3, 512)         1839744   
_________________________________________________________________
global_average_pooling2d_1 ( (None, 512)               0         
_________________________________________________________________
dense_14 (Dense)             (None, 10)                5130      
Total params: 2,400,490
Trainable params: 2,397,418
Non-trainable params: 3,072
_____________________________________________

[0.15059037506580353, 0.9559999704360962]

In [ ]:
#building Custom layers

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

#building custom models
class Dense(layers.Layer):
  def __init__(self, units ): #input_dim
    super(Dense, self).__init__()
    self.units = units
    
  #build dim, if given, then there would be no need of paramete input_Weight
  def build(self, input_shape):
    self.w = self.add_weight(
        name = 'w',
        shape = (input_shape[-1], self.units),
        initializer = 'random_normal',
        trainable = True,
    )

    self.b = self.add_weight(
        name = 'b',
        shape = (self.units),
        initializer = 'zeros',
        trainable = True,
    )

  def call(self,inputs):
    return tf.matmul(inputs, self.w) + self.b

#custom ReLu function
class MyReLu(layers.Layer):
  def __init__(self):
    super(MyReLu, self).__init__()

  def call(self, x):
    return tf.math.maximum(x,0)

class MyModel(keras.Model):
  def __init__(self, num_classes = 10):
    super(MyModel, self).__init__()
    # self.dense1 = layers.Dense(64)
    # self.dense2 = layers.Dense(num_classes)

    #custom layers with input dimension and without build method
    # self.dense1 = Dense(64,784)
    # self.dense2 = Dense(10,64)

    #with build method
    self.dense1 = Dense(64)
    self.dense2 = Dense(num_classes)
    self.relu = MyReLu()

  def call(self, x):
    x = self.relu(self.dense1(x))
    return self.dense2(x)

model = MyModel()
model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

model.fit(x_train, y_train, batch_size = 32, epochs = 2, verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)

Epoch 1/2
1875/1875 - 3s - loss: 0.3436 - accuracy: 0.9071
Epoch 2/2
1875/1875 - 2s - loss: 0.1637 - accuracy: 0.9521
313/313 - 0s - loss: 0.1426 - accuracy: 0.9587


[0.1425895392894745, 0.9587000012397766]

In [21]:
#saving and loading model weights and 
#saving and loading entire model(serializing model)
# - save weights
# - model architecture
# - Training config(model.compile())
# - Optimizer and states

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

#first model using Sequential API
model1 = keras.Sequential(
    [
     layers.Dense(64, activation = 'relu'),
     layers.Dense(10),
    ]
)

#second model using functional API
inputs = keras.Input(784)
x = layers.Dense(64, activation = 'relu')(inputs)
outputs = layers.Dense(10)(x)

model2 = keras.Model(inputs = inputs, outputs = outputs)

#model 3 by subclassing
class MyModel(keras.Model):
  def __init__(self):
    super(MyModel, self).__init__()
    self.dense1 = layers.Dense(64,activation = 'relu')
    self.dense2 = layers.Dense(10)

  def call(self, input_tensor):
    x = tf.nn.relu(self.dense1(input_tensor))
    return self.dense2(x)

model3 = MyModel()

model = model1

#to load the saved model
model.load_weights('saved_model/')
#general rule is you have to load the model in same way as it has been saved
#can't load a model in functional API if it has been saved in Sequential API
#that might require some extra techniques


# model.compile(
#     optimizer = keras.optimizers.Adam(),
#     loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#     metrics = ["accuracy"],
# )
model = keras.models.load_model('complete_saved_model/')
#we can also remove the code because everything will be done in load_model
#this load_model is irrespective of the APIs used

model.fit(x_train, y_train, batch_size = 32, epochs = 2, verbose = 2)
model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)

#to save the model
# model.save_weights(#directory name
#                     'saved_model/')
#when saving the model there are diff formats
#either the default model or h5

#saving the entire model and serialising the model
model.save('complete_saved_model/')
#after saving we remove the model.compile and replace it

NotFoundError: ignored

In [33]:
#transfer learning, pretrained model, tf-hub
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import tensorflow_hub as hub
 
#pretrained model....
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0 #this is being done to normalise the values of greyscale b/w 0 and 1, and float64 is being converted to float32 for ease in computation
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0

model = keras.models.load_model("/content/complete_saved_model")
# print(model.summary)

#{if we wanna freeze the layers from this pretrained model and 
#not wanna actually train it for fine tuning then we have to write the following 
#commant and set the trainable attribute to False}
model.trainable = False

#to freeze specific layers, we can iterate through layers and freeze specific ones:
for layer in model.layers:
  assert layer.trainable == False
  layer.trainable = False

#we take the first layer from the loaded model and take in the input layer
#and take the second last layer and make a top layer over the final layer which we'll define ourselves
base_inputs = model.layers[0].input
base_outputs = model.layers[-2].output

output = layers.Dense(15)(base_outputs)

new_model = keras.Model(inputs = base_inputs, outputs = output)
print(new_model.summary())

new_model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

new_model.fit(x_train, y_train, batch_size = 32, epochs = 2, verbose = 2)
new_model.evaluate(x_test, y_test, batch_size = 32, verbose = 2)


Model: "model_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18_input (InputLayer)  [(None, 784)]             0         
_________________________________________________________________
dense_18 (Dense)             (None, 64)                50240     
_________________________________________________________________
dense_38 (Dense)             (None, 15)                975       
Total params: 51,215
Trainable params: 975
Non-trainable params: 50,240
_________________________________________________________________
None
Epoch 1/2
1875/1875 - 2s - loss: 0.4009 - accuracy: 0.8957
Epoch 2/2
1875/1875 - 2s - loss: 0.0685 - accuracy: 0.9826
313/313 - 0s - loss: 0.0884 - accuracy: 0.9750


[0.08836004883050919, 0.9750000238418579]

In [35]:
#transfer learning, *pretrained model*, tf-hub
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import tensorflow_hub as hub
 
x = tf.random.normal(shape = (5,299,299,3))
y = tf.constant([0,1,2,3,4])

model = keras.applications.InceptionV3(include_top = True)
#include_top would remove the final fully connected layers 
#enables to get the feature vectors to define our own sequential model
#print(model.summary())

base_inputs = model.layers[0].input
base_outputs = model.layers[-2].output

output = layers.Dense(5)(base_outputs)

new_model = keras.Model(inputs = base_inputs, outputs = output)
print(new_model.summary())

new_model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

new_model.fit(x, y, batch_size = 32, epochs = 15, verbose = 2)
#here also, for fine tuning, base_model.Trainable can be set to False

Model: "model_9"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_8 (InputLayer)            [(None, 299, 299, 3) 0                                            
__________________________________________________________________________________________________
conv2d_94 (Conv2D)              (None, 149, 149, 32) 864         input_8[0][0]                    
__________________________________________________________________________________________________
batch_normalization_94 (BatchNo (None, 149, 149, 32) 96          conv2d_94[0][0]                  
__________________________________________________________________________________________________
activation_94 (Activation)      (None, 149, 149, 32) 0           batch_normalization_94[0][0]     
____________________________________________________________________________________________

In [36]:
#using tensorflow hub data

import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist
import tensorflow_hub as hub
 
x = tf.random.normal(shape = (5,299,299,3))
y = tf.constant([0,1,2,3,4])

url = 'https://tfhub.dev/google/imagenet/inception_v3/feature_vector/5'

base_model = hub.KerasLayer(url, input_shape = (299,299,3))
base_model.Trainable = False

model = keras.Sequential(
    [
     base_model,
     layers.Dense(128, activation = 'relu'),
     layers.Dense(64, activation = 'relu'),
     layers.Dense(5),
    ]
)

model.compile(
    optimizer = keras.optimizers.Adam(),
    loss = keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics = ["accuracy"],
)

model.fit(x, y, batch_size = 32, epochs = 15, verbose = 2)


Epoch 1/15
1/1 - 5s - loss: 1.6553 - accuracy: 0.0000e+00
Epoch 2/15
1/1 - 1s - loss: 1.5183 - accuracy: 0.4000
Epoch 3/15
1/1 - 1s - loss: 1.4159 - accuracy: 0.6000
Epoch 4/15
1/1 - 1s - loss: 1.2994 - accuracy: 1.0000
Epoch 5/15
1/1 - 1s - loss: 1.1844 - accuracy: 1.0000
Epoch 6/15
1/1 - 1s - loss: 1.0548 - accuracy: 1.0000
Epoch 7/15
1/1 - 1s - loss: 0.9481 - accuracy: 1.0000
Epoch 8/15
1/1 - 1s - loss: 0.8416 - accuracy: 1.0000
Epoch 9/15
1/1 - 1s - loss: 0.7328 - accuracy: 1.0000
Epoch 10/15
1/1 - 1s - loss: 0.6426 - accuracy: 1.0000
Epoch 11/15
1/1 - 1s - loss: 0.5582 - accuracy: 1.0000
Epoch 12/15
1/1 - 1s - loss: 0.4784 - accuracy: 1.0000
Epoch 13/15
1/1 - 1s - loss: 0.4079 - accuracy: 1.0000
Epoch 14/15
1/1 - 1s - loss: 0.3441 - accuracy: 1.0000
Epoch 15/15
1/1 - 1s - loss: 0.2896 - accuracy: 1.0000
